openapi: 3.0.0
info:
  title: DevC Capstone Projectc
  description: "Description"
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: "description"
  - url: http://staging-api.example.com
    description:  "description"
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string